name: WMATA Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:

  deploy-lambda:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Lambda dependencies
        run: pip install -r requirements.txt

      - name: Install pip dependencies into package
        run: |
          mkdir -p package
          cp lambda/*.py package/
          pip install --target ./package -r requirements.txt --no-cache-dir

      - name: Zip Lambda function
        run: |
          cd package
          zip -r ../lambda.zip . -x "*.pyc" -x "*__pycache__*"
          cd ..

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name WMATA-fare-api \
            --zip-file fileb://lambda.zip \
            --region $AWS_REGION

  deploy-ui:
    name: Deploy React Frontend to S3
    runs-on: ubuntu-latest
    env:
      S3_BUCKET: wmata-fares
      S3_PREFIX: ""
      REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: app
        run: npm ci

      - name: Build React app
        working-directory: app
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync app/build/ s3://$S3_BUCKET/$S3_PREFIX/ \
            --delete 
